repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]
        exclude: package-lock.json|.secrets.baseline

  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.3
    hooks:
      - id: bandit
        args: ["-r", "SistemaRegistro", "-x", "./venv,./tests,./SIN_USO,./old,./backup,./scripts,registry/tests,users/tests,simplified_test.py,verificar_estadisticas.py,registry/migrations,SistemaRegistro/settings.py,registry/context_processors.py,users/views.py"]
        pass_filenames: false

  - repo: https://github.com/pypa/pip-audit
    rev: v2.10.0
    hooks:
      - id: pip-audit
        args: ["-r", "SistemaRegistro/requirements.txt"]
        files: "requirements.txt"
        pass_filenames: false
