version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=robotica_db
      - POSTGRES_USER=msathiu
      - POSTGRES_PASSWORD=tu_password_segura
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./SistemaRegistro:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://msathiu:tu_password_segura@db:5432/robotica_db
    depends_on:
      - db

volumes:
  postgres_data:
