# Generated by Django 5.2.6 on 2025-12-10 22:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participante',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='participante',
            name='telefono_representante',
        ),
        migrations.AddField(
            model_name='participante',
            name='codigo_area',
            field=models.CharField(choices=[('0424', '0424 (Movistar)'), ('0414', '0414 (Movistar)'), ('0412', '0412 (Digitel)'), ('0426', '0426 (Movilnet)'), ('0416', '0416 (Movilnet)'), ('0422', '0422 (Digitel)')], default='0424', max_length=4, verbose_name='Código de Área'),
        ),
        migrations.AddField(
            model_name='participante',
            name='codigo_area_representante',
            field=models.CharField(blank=True, choices=[('0424', '0424 (Movistar)'), ('0414', '0414 (Movistar)'), ('0412', '0412 (Digitel)'), ('0426', '0426 (Movilnet)'), ('0416', '0416 (Movilnet)'), ('0422', '0422 (Digitel)')], max_length=4, verbose_name='Cód. Área Rep.'),
        ),
        migrations.AddField(
            model_name='participante',
            name='numero_telefono',
            field=models.CharField(default=0, max_length=7, validators=[django.core.validators.RegexValidator(message='El número debe ser de 7 dígitos numéricos.', regex='^[0-9]{7}$')], verbose_name='Número (7 dígitos)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participante',
            name='numero_telefono_representante',
            field=models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator(message='El número debe ser de 7 dígitos numéricos.', regex='^[0-9]{7}$')], verbose_name='Número Rep. (7 dígitos)'),
        ),
    ]
