# Generated by Django 5.2.6 on 2026-02-09 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0002_club"),
    ]

    operations = [
        migrations.AddField(
            model_name="institucion",
            name="dependencia",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
