# Generated by Django 5.2.6 on 2025-12-10 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_remove_participante_telefono_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='nombre_escuela',
            field=models.CharField(blank=True, help_text='Nombre del centro de estudio actual.', max_length=200, verbose_name='Nombre de la Escuela/Universidad'),
        ),
        migrations.AlterField(
            model_name='participante',
            name='codigo_area',
            field=models.CharField(choices=[('0424', '0424'), ('0414', '0414'), ('0412', '0412'), ('0426', '0426'), ('0416', '0412'), ('0422', '0422')], default='0424', max_length=4, verbose_name='Código de Área'),
        ),
        migrations.AlterField(
            model_name='participante',
            name='codigo_area_representante',
            field=models.CharField(blank=True, choices=[('0424', '0424'), ('0414', '0414'), ('0412', '0412'), ('0426', '0426'), ('0416', '0412'), ('0422', '0422')], max_length=4, verbose_name='Cód. Área Rep.'),
        ),
        migrations.AlterField(
            model_name='participante',
            name='grado_escolar',
            field=models.CharField(choices=[('NO', 'No estudia'), ('P1', 'Preescolar Nivel 1'), ('P2', 'Preescolar Nivel 2'), ('PR1', '1er Grado Primaria'), ('PR2', '2do Grado Primaria'), ('PR3', '3er Grado Primaria'), ('PR4', '4to Grado Primaria'), ('PR5', '5to Grado Primaria'), ('PR6', '6to Grado Primaria'), ('L1', '1er Año Liceo'), ('L2', '2do Año Liceo'), ('L3', '3er Año Liceo'), ('L4', '4to Año Liceo'), ('L5', '5to Año Liceo'), ('L6', '6to Año Liceo'), ('U', 'Estudios Universitarios'), ('OTRO', 'Otro/No especificado')], default='NO', max_length=4, verbose_name='Nivel Educativo/Grado'),
        ),
    ]
