# Generated by Django 5.2.6 on 2025-12-12 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_participante_nombre_escuela_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='codigo_area',
            field=models.CharField(choices=[('0424', '0424'), ('0414', '0414'), ('0422', '0422'), ('0412', '0412'), ('0426', '0426'), ('0416', '0416')], default='0424', max_length=4, verbose_name='Código de Área'),
        ),
        migrations.AlterField(
            model_name='participante',
            name='codigo_area_representante',
            field=models.CharField(blank=True, choices=[('0424', '0424'), ('0414', '0414'), ('0422', '0422'), ('0412', '0412'), ('0426', '0426'), ('0416', '0416')], max_length=4, verbose_name='Cód. Área Rep.'),
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registry.estado')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.institucion')),
            ],
        ),
    ]
