# Generated by Django 5.2.6 on 2025-12-29 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0005_inscripcion_integranteequipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institucion',
            name='activa',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='codigo',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
