# Generated by Django 5.2.6 on 2026-01-16 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0006_alter_institucion_activa_alter_institucion_codigo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estado',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='municipio',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterField(
            model_name='municipio',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipios', to='registry.estado'),
        ),
    ]
