# Generated by Django 5.2.6 on 2026-01-28 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0006_alter_institucion_activa_alter_institucion_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='institucion',
            name='rif',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
