# Generated by Django 5.2.6 on 2026-02-11 05:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0007_dependencia_institucion_categoria_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="institucion",
            name="federado",
            field=models.BooleanField(default=False, verbose_name="Federado"),
        ),
    ]
