# Generated by Django 5.2.6 on 2026-02-11 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0008_institucion_federado"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="club",
            options={
                "ordering": ["nombre"],
                "verbose_name": "Club",
                "verbose_name_plural": "Clubes",
            },
        ),
        migrations.AlterModelOptions(
            name="evento",
            options={
                "ordering": ["-fecha"],
                "verbose_name": "Evento",
                "verbose_name_plural": "Eventos",
            },
        ),
        migrations.AlterModelOptions(
            name="institucion",
            options={
                "ordering": ["nombre"],
                "verbose_name": "Institución",
                "verbose_name_plural": "Instituciones",
            },
        ),
        migrations.AlterModelOptions(
            name="participante",
            options={
                "ordering": ["apellidos", "nombres"],
                "verbose_name": "Participante",
                "verbose_name_plural": "Participantes",
            },
        ),
        migrations.AddField(
            model_name="club",
            name="activo",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name="club",
            name="fecha_creacion",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name="evento",
            name="activo",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name="evento",
            name="fecha_creacion",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name="grupo",
            name="activo",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="club",
            name="nombre",
            field=models.CharField(
                db_index=True, max_length=200, verbose_name="Nombre del Club"
            ),
        ),
        migrations.AlterField(
            model_name="dependencia",
            name="activa",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="dependencia",
            name="nombre",
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="estado",
            name="codigo",
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name="estado",
            name="nombre",
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="evento",
            name="estado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="registry.estado",
            ),
        ),
        migrations.AlterField(
            model_name="evento",
            name="fecha",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="evento",
            name="nombre",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="grupo",
            name="nombre",
            field=models.CharField(
                db_index=True, max_length=150, verbose_name="Nombre del Grupo"
            ),
        ),
        migrations.AlterField(
            model_name="grupo",
            name="tutor_cedula",
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="municipio",
            name="nombre",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="parroquia",
            name="nombre",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name="club",
            index=models.Index(
                fields=["activo", "nombre"], name="idx_club_activo_nombre"
            ),
        ),
        migrations.AddIndex(
            model_name="dependencia",
            index=models.Index(
                fields=["activa", "nombre"], name="idx_dep_activa_nombre"
            ),
        ),
        migrations.AddIndex(
            model_name="estado",
            index=models.Index(fields=["nombre"], name="idx_estado_nombre"),
        ),
        migrations.AddIndex(
            model_name="estado",
            index=models.Index(fields=["codigo"], name="idx_estado_codigo"),
        ),
        migrations.AddIndex(
            model_name="evento",
            index=models.Index(fields=["fecha", "activo"], name="idx_evt_fecha_activo"),
        ),
        migrations.AddIndex(
            model_name="evento",
            index=models.Index(fields=["institucion"], name="idx_evt_institucion"),
        ),
        migrations.AddIndex(
            model_name="grupo",
            index=models.Index(
                fields=["usuario_creador", "activo"], name="idx_grp_creador_activo"
            ),
        ),
        migrations.AddIndex(
            model_name="grupo",
            index=models.Index(fields=["evento"], name="idx_grp_evento"),
        ),
        migrations.AddIndex(
            model_name="institucion",
            index=models.Index(fields=["codigo"], name="idx_inst_codigo"),
        ),
        migrations.AddIndex(
            model_name="institucion",
            index=models.Index(fields=["email"], name="idx_inst_email"),
        ),
        migrations.AddIndex(
            model_name="institucion",
            index=models.Index(fields=["estatus"], name="idx_inst_estatus"),
        ),
        migrations.AddIndex(
            model_name="institucion",
            index=models.Index(fields=["activa"], name="idx_inst_activa"),
        ),
        migrations.AddIndex(
            model_name="institucion",
            index=models.Index(
                fields=["estado", "municipio"], name="idx_inst_ubicacion"
            ),
        ),
        migrations.AddIndex(
            model_name="institucion",
            index=models.Index(fields=["tipo_institucion"], name="idx_inst_tipo"),
        ),
        migrations.AddIndex(
            model_name="institucion",
            index=models.Index(fields=["federado"], name="idx_inst_federado"),
        ),
        migrations.AddIndex(
            model_name="municipio",
            index=models.Index(
                fields=["estado", "nombre"], name="idx_mun_estado_nombre"
            ),
        ),
        migrations.AddIndex(
            model_name="parroquia",
            index=models.Index(
                fields=["municipio", "nombre"], name="idx_parr_mun_nombre"
            ),
        ),
        migrations.AddIndex(
            model_name="participante",
            index=models.Index(fields=["cedula"], name="idx_part_cedula"),
        ),
        migrations.AddIndex(
            model_name="participante",
            index=models.Index(fields=["email"], name="idx_part_email"),
        ),
        migrations.AddIndex(
            model_name="participante",
            index=models.Index(fields=["institucion"], name="idx_part_inst"),
        ),
        migrations.AddIndex(
            model_name="participante",
            index=models.Index(
                fields=["estado", "municipio"], name="idx_part_ubicacion"
            ),
        ),
        migrations.AddIndex(
            model_name="participante",
            index=models.Index(fields=["activo"], name="idx_part_activo"),
        ),
        migrations.AddIndex(
            model_name="participante",
            index=models.Index(fields=["apellidos", "nombres"], name="idx_part_nombre"),
        ),
    ]
