# Generated by Django 5.2.6 on 2026-02-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0008_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='institucion',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='institucion',
            name='fecha_eliminacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
