# Generated by Django 5.2.6 on 2026-02-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0009_institucion_eliminado_institucion_fecha_eliminacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='institucion',
            name='tipo_federado',
            field=models.CharField(choices=[('institucion', 'Institución Educativa'), ('organizacion', 'Organización / Club'), ('particular', 'Particular / Independiente')], default='institucion', max_length=20),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='rif',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
