# Generated by Django 5.2.6 on 2026-02-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0011_sistema_institucional"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grupo",
            name="codigo",
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
