# Generated by Django 5.2.6 on 2026-02-17 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0012_alter_grupo_codigo"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="grupo",
            name="idx_grp_creador_activo",
        ),
        migrations.RemoveIndex(
            model_name="grupo",
            name="idx_grp_evento",
        ),
        migrations.AddField(
            model_name="evento",
            name="cancelado",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="evento",
            name="capacidad_maxima",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="evento",
            name="direccion",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="evento",
            name="fecha_actualizacion",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="evento",
            name="motivo_cancelacion",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="evento",
            name="municipio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="registry.municipio",
            ),
        ),
        migrations.AddField(
            model_name="evento",
            name="parroquia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="registry.parroquia",
            ),
        ),
        migrations.AddField(
            model_name="evento",
            name="requisitos",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="grupo",
            name="tutor_apellidos",
            field=models.CharField(blank=True, default="", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="grupo",
            name="tutor_cedula",
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="grupo",
            name="tutor_nombre",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="grupo",
            name="tutor_telefono",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
