# Generated by Django 5.2.6 on 2026-02-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0013_add_municipio_parroquia_to_evento"),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="categoria",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
