# Generated by Django 5.2.6 on 2026-03-07 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0037_agregar_campos_criterio_grupo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='tutor_apellidos',
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='tutor_cedula',
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='tutor_nombre',
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='tutor_telefono',
        ),
    ]
