# Generated by Django 5.2.6 on 2026-03-07 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_agregar_audiencia_eventos'),
        ('registry', '0038_remove_grupo_tutor_apellidos_and_more'),
    ]

    operations = [
    ]
