# Generated by Django 5.2.6 on 2026-03-08 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0039_remove_old_tutor_fields'),
        ('registry', '0041_alter_evento_tipo'),
    ]

    operations = [
    ]
