# Generated by Django 5.2.6 on 2026-03-09 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0049_fix_all_participante_fk_uuid'),
        ('registry', '0050_add_participante_unique_constraints'),
    ]

    operations = [
    ]
