# Generated by Django 5.2.6 on 2026-03-10 02:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0002_add_sexo_to_tutor"),
        ("registry", "0051_merge_20260308_2008"),
    ]

    operations = []
