# Generated by Django 5.2.6 on 2026-03-11 06:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0052_merge_0002_add_sexo_to_tutor_0051_merge_20260308_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='telefono_codigo',
            field=models.CharField(blank=True, choices=[('0424', '0424'), ('0414', '0414'), ('0422', '0422'), ('0412', '0412'), ('0426', '0426'), ('0416', '0416'), ('0212', '0212')], help_text='Código de área del teléfono de contacto', max_length=4, verbose_name='Código de Área'),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='naturaleza',
            field=models.CharField(blank=True, choices=[('publica', 'Pública'), ('privada', 'Privada')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='tipo_institucion',
            field=models.CharField(choices=[('educativa', 'Institución Educativa (Adscrita a MPPE)'), ('publica', 'Pública'), ('privada', 'Privada'), ('otra', 'Otras Instituciones'), ('particular', 'Particular (Persona Natural)')], default='educativa', max_length=20),
        ),
        migrations.AlterField(
            model_name='participante',
            name='codigo_area',
            field=models.CharField(choices=[('0424', '0424'), ('0414', '0414'), ('0422', '0422'), ('0412', '0412'), ('0426', '0426'), ('0416', '0416'), ('0212', '0212')], default='0424', max_length=4, verbose_name='Código de Área'),
        ),
        migrations.AlterField(
            model_name='participante',
            name='codigo_area_representante',
            field=models.CharField(blank=True, choices=[('0424', '0424'), ('0414', '0414'), ('0422', '0422'), ('0412', '0412'), ('0426', '0426'), ('0416', '0416'), ('0212', '0212')], max_length=4, verbose_name='Cód. Área Rep.'),
        ),
        migrations.AlterField(
            model_name='participante',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='telefono_codigo',
            field=models.CharField(blank=True, choices=[('0424', '0424'), ('0414', '0414'), ('0422', '0422'), ('0412', '0412'), ('0426', '0426'), ('0416', '0416'), ('0212', '0212')], help_text='Código de área del teléfono de contacto', max_length=4, verbose_name='Código de Área'),
        ),
    ]
