# Generated by Django 5.2.6 on 2026-03-08 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0047_fix_grupo_participantes_uuid'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name = 'registry_participanteinstitucion' 
                    AND column_name = 'participante_id'
                    AND data_type != 'uuid'
                ) THEN
                    ALTER TABLE registry_participanteinstitucion 
                    ALTER COLUMN participante_id TYPE uuid USING participante_id::text::uuid;
                END IF;
            END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
