# Generated by Django 5.2.6 on 2026-03-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "1004_evento_fecha_hasta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institucion",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
