# Generated by Django 5.2.6 on 2026-03-21 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '1005_alter_institucion_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participante',
            name='nombre_escuela',
        ),
    ]
