# Generated by Django 5.2.6 on 2026-03-24 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "1009_alter_participanteinstitucion_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutorinstitucion",
            name="rol",
            field=models.CharField(
                choices=[
                    ("asistente", "Asistente"),
                    ("entrenador", "Entrenador"),
                    ("instructor", "Instructor/Monitor"),
                    ("coordinador", "Coordinador"),
                    ("delegado", "Delegado"),
                    ("representante", "Representante"),
                    ("colaborador", "Colaborador"),
                ],
                default="colaborador",
                max_length=20,
                verbose_name="Rol",
            ),
        ),
        migrations.CreateModel(
            name="ClubTutor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rol",
                    models.CharField(
                        choices=[
                            ("responsable", "Responsable del Club"),
                            ("coordinador", "Coordinador"),
                            ("entrenador", "Entrenador"),
                            ("instructor", "Instructor"),
                            ("colaborador", "Colaborador"),
                            ("representante", "Representante"),
                            ("director", "Director Ejecutivo"),
                            ("delegado", "Delegado"),
                            ("asistente", "Asistente"),
                            ("logistico", "Logística"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("activo", "Activo"), ("inactivo", "Inactivo")],
                        default="activo",
                        max_length=20,
                    ),
                ),
                ("fecha_asignacion", models.DateTimeField(auto_now_add=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tutores",
                        to="registry.club",
                    ),
                ),
                (
                    "tutor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clubes",
                        to="registry.tutor",
                    ),
                ),
            ],
            options={
                "unique_together": {("club", "tutor")},
            },
        ),
    ]
