# Generated by Django 5.2.6 on 2026-03-31 01:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "1010_alter_tutorinstitucion_rol_clubtutor"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="tipo_creador",
            field=models.CharField(
                choices=[
                    ("institucion", "Institución"),
                    ("fed_central", "Federación Central"),
                    ("fed_regional", "Sede Regional"),
                ],
                default="institucion",
                help_text="Indica si el club fue creado por una institución, federación central o sede regional",
                max_length=20,
                verbose_name="Tipo de Creador",
            ),
        ),
    ]
