# Generated by Django 5.2.6 on 2026-04-06 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '1013_alter_asistenciaevento_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistenciaevento',
            name='participante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asistencias', to='registry.participante'),
        ),
    ]
