# Generated by Django 5.2.13 on 2026-05-06 01:58

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '1015_load_guayana_esequiba'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='institucion',
            name='codigo_infocentro',
            field=models.CharField(blank=True, help_text='Código alfanumérico de máximo 5 caracteres para Infocentros', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='telefono_codigo',
            field=models.CharField(blank=True, choices=[('0424', '0424'), ('0414', '0414'), ('0422', '0422'), ('0412', '0412'), ('0426', '0426'), ('0416', '0416'), ('0212', '0212'), ('0241', '0241'), ('0251', '0251'), ('0281', '0281')], help_text='Código de área del teléfono de contacto', max_length=4, verbose_name='Código de Área'),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='particular_cedula',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(7), django.core.validators.MaxLengthValidator(10)], verbose_name='Cédula (solo números)'),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='tipo_institucion',
            field=models.CharField(choices=[('educativa', 'Institución Educativa (Adscrita a MPPE)'), ('publica', 'Pública'), ('privada', 'Privada'), ('otra', 'Otras Instituciones'), ('particular', 'Particular (Persona Natural)'), ('infocentro', 'Infocentro')], default='educativa', max_length=20),
        ),
        migrations.AlterField(
            model_name='participante',
            name='codigo_area',
            field=models.CharField(choices=[('0424', '0424'), ('0414', '0414'), ('0422', '0422'), ('0412', '0412'), ('0426', '0426'), ('0416', '0416'), ('0212', '0212'), ('0241', '0241'), ('0251', '0251'), ('0281', '0281')], default='0424', max_length=4, verbose_name='Código de Área'),
        ),
        migrations.AlterField(
            model_name='participante',
            name='codigo_area_representante',
            field=models.CharField(blank=True, choices=[('0424', '0424'), ('0414', '0414'), ('0422', '0422'), ('0412', '0412'), ('0426', '0426'), ('0416', '0416'), ('0212', '0212'), ('0241', '0241'), ('0251', '0251'), ('0281', '0281')], max_length=4, verbose_name='Cód. Área Rep.'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='telefono_codigo',
            field=models.CharField(blank=True, choices=[('0424', '0424'), ('0414', '0414'), ('0422', '0422'), ('0412', '0412'), ('0426', '0426'), ('0416', '0416'), ('0212', '0212'), ('0241', '0241'), ('0251', '0251'), ('0281', '0281')], help_text='Código de área del teléfono de contacto', max_length=4, verbose_name='Código de Área'),
        ),
        migrations.AddConstraint(
            model_name='institucion',
            constraint=models.UniqueConstraint(condition=models.Q(('eliminado', False), ('tipo_institucion', 'educativa')), fields=('codigo_mppe',), name='unique_codigo_mppe_educativas'),
        ),
        migrations.AddConstraint(
            model_name='institucion',
            constraint=models.UniqueConstraint(condition=models.Q(('eliminado', False), ('tipo_institucion__in', ['publica', 'privada', 'otra'])), fields=('rif', 'estado', 'municipio', 'parroquia'), name='unique_rif_ubicacion_regulares'),
        ),
        migrations.AddConstraint(
            model_name='institucion',
            constraint=models.UniqueConstraint(condition=models.Q(('eliminado', False), ('tipo_institucion', 'infocentro')), fields=('codigo_infocentro',), name='unique_codigo_infocentro_infocentros'),
        ),
        migrations.AddConstraint(
            model_name='institucion',
            constraint=models.UniqueConstraint(condition=models.Q(('eliminado', False), ('tipo_institucion', 'infocentro')), fields=('estado', 'municipio', 'parroquia'), name='unique_ubicacion_infocentros'),
        ),
        migrations.AddConstraint(
            model_name='institucion',
            constraint=models.UniqueConstraint(condition=models.Q(('eliminado', False), ('tipo_institucion', 'particular')), fields=('particular_cedula',), name='unique_cedula_particulares'),
        ),
    ]
