# Generated by Django 5.2.13 on 2026-04-22 01:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "1015_load_guayana_esequiba"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # migrations.AddConstraint(
        #     model_name="institucion",
        #     constraint=models.UniqueConstraint(
        #         condition=models.Q(
        #             ("eliminado", False), ("tipo_institucion", "educativa")
        #         ),
        #         fields=("codigo_mppe",),
        #         name="unique_codigo_mppe_educativas",
        #     ),
        # ),
        # migrations.AddConstraint(
        #     model_name="institucion",
        #     constraint=models.UniqueConstraint(
        #         condition=models.Q(
        #             ("eliminado", False),
        #             ("tipo_institucion__in", ["publica", "privada", "otra"]),
        #         ),
        #         fields=("rif", "estado", "municipio", "parroquia"),
        #         name="unique_rif_ubicacion_regulares",
        #     ),
        # ),
        # migrations.AddConstraint(
        #     model_name="institucion",
        #     constraint=models.UniqueConstraint(
        #         condition=models.Q(
        #             ("eliminado", False), ("tipo_institucion", "particular")
        #         ),
        #         fields=("particular_cedula",),
        #         name="unique_cedula_particulares",
        #     ),
        # ),
    ]
