# Generated by Django 5.2.13 on 2026-05-01 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '1017_expand_codigo_area_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='telefono_codigo',
            field=models.CharField(blank=True, choices=[('0424', '0424'), ('0414', '0414'), ('0422', '0422'), ('0412', '0412'), ('0426', '0426'), ('0416', '0416'), ('0212', '0212'), ('0241', '0241'), ('0251', '0251'), ('0281', '0281')], help_text='Código de área del teléfono de contacto', max_length=4, verbose_name='Código de Área'),
        ),
        migrations.AlterField(
            model_name='participante',
            name='codigo_area_representante',
            field=models.CharField(blank=True, choices=[('0424', '0424'), ('0414', '0414'), ('0422', '0422'), ('0412', '0412'), ('0426', '0426'), ('0416', '0416'), ('0212', '0212'), ('0241', '0241'), ('0251', '0251'), ('0281', '0281')], max_length=4, verbose_name='Cód. Área Rep.'),
        ),
    ]
