# Generated by Django 5.2.13 on 2026-05-02 04:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '1018_alter_evento_telefono_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institucion',
            name='particular_cedula',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(7), django.core.validators.MaxLengthValidator(10)], verbose_name='Cédula (solo números)'),
        ),
    ]
