# Generated by Django 5.2.13 on 2026-05-05 05:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '1019_alter_institucion_particular_cedula'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='institucion',
            name='codigo_infocentro',
            field=models.CharField(blank=True, help_text='Código alfanumérico de máximo 5 caracteres para Infocentros', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='tipo_institucion',
            field=models.CharField(choices=[('educativa', 'Institución Educativa (Adscrita a MPPE)'), ('publica', 'Pública'), ('privada', 'Privada'), ('otra', 'Otras Instituciones'), ('particular', 'Particular (Persona Natural)'), ('infocentro', 'Infocentro')], default='educativa', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='institucion',
            constraint=models.UniqueConstraint(condition=models.Q(eliminado=False, tipo_institucion='infocentro'), fields=('codigo_infocentro',), name='unique_codigo_infocentro_infocentros'),
        ),
        migrations.AddConstraint(
            model_name='institucion',
            constraint=models.UniqueConstraint(condition=models.Q(eliminado=False, tipo_institucion='infocentro'), fields=('estado', 'municipio', 'parroquia'), name='unique_ubicacion_infocentros'),
        ),
    ]
