# Generated by Django 5.2.6 on 2026-01-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('id_estado', models.IntegerField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=100)),
                ('iso_3166_2', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'estados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Municipios',
            fields=[
                ('id_municipio', models.IntegerField(primary_key=True, serialize=False)),
                ('municipio', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'municipios',
                'managed': False,
            },
        ),
    ]
