from .base import (
    CODIGO_AREA_CHOICES,
    GRADO_CHOICES,
    NACIONALIDAD_CHOICES,
    NUMERO_VALIDATOR,
    SEXO_CHOICES,
    Dependencia,
    Estado,
    Municipio,
    Parroquia,
    normalizar_texto_titulo,
)
from .club import (
    CalificacionClub,
    Club,
    ClubLineaInvestigacion,
    ComentarioClub,
    HistorialClub,
    MembresiaClu,
    SolicitudEliminacionClub,
)
from .evento import (
    ESTADOS_EDITABLES,
    ESTADOS_FINALES,
    ESTADOS_INSCRIBIBLES,
    TRANSICIONES_VALIDAS,
    ClubEvento,
    EstadoEvento,
    Evento,
    EventoManager,
    Inscripcion,
    InscripcionGrupoEvento,
    IntegranteEquipo,
)
from .grupo import Grupo
from .institucion import Institucion
from .investigacion import LineaInvestigacion
from .notificacion import Notificacion
from .participante import (
    AsistenciaEvento,
    Participante,
    ParticipanteGrupo,
    ParticipanteInstitucion,
)
from .tutor import Tutor, TutorInstitucion

__all__ = [
    "normalizar_texto_titulo",
    "normalizar_texto_titulo_op",
    "NACIONALIDAD_CHOICES",
    "SEXO_CHOICES",
    "CODIGO_AREA_CHOICES",
    "GRADO_CHOICES",
    "NUMERO_VALIDATOR",
    "Estado",
    "Municipio",
    "Parroquia",
    "Dependencia",
    "LineaInvestigacion",
    "Institucion",
    "Participante",
    "ParticipanteInstitucion",
    "ParticipanteGrupo",
    "AsistenciaEvento",
    "Tutor",
    "TutorInstitucion",
    "Evento",
    "EventoManager",
    "EstadoEvento",
    "TRANSICIONES_VALIDAS",
    "ESTADOS_FINALES",
    "ESTADOS_EDITABLES",
    "ESTADOS_INSCRIBIBLES",
    "Inscripcion",
    "IntegranteEquipo",
    "InscripcionGrupoEvento",
    "ClubEvento",
    "Grupo",
    "Club",
    "MembresiaClu",
    "SolicitudEliminacionClub",
    "HistorialClub",
    "ComentarioClub",
    "CalificacionClub",
    "ClubLineaInvestigacion",
    "Notificacion",
]
